import type { Flow } from "../../harness/types";

export const flows: Flow[] = [
  {
    id: "home",
    flow: "home",
    label: "Console home: the phone is the remote",
    start: "home.02-tv-console-home",
    steps: [
      { device: "phone", bot: "act-bake-shop", mark: "Tap Bake Shop on the phone: the TV home turns to it", wait: 1800 },
      { device: "phone", bot: "play-on-tv", mark: "Play on TV: day 4 opens, Juneau's iPad drops into his seat", wait: 2400 },
    ],
  },
  {
    id: "swap",
    flow: "swap",
    label: "Rocket Crew mission 6 → Bake Shop day 4, every device",
    start: "swap.01-mid-rocket-crew",
    steps: [
      { device: "phone", bot: "console-home", mark: "Dad presses the console button: Rocket Crew pauses on the TV, the next games come up", wait: 1800 },
      { device: "phone", bot: "next-bake-shop", mark: "Picks Bake Shop: mission 6 saves, the TV cuts over, Juneau's iPad follows on its own", wait: 5600 },
    ],
  },
  {
    id: "swap-undo",
    flow: "swap",
    label: "Changed our minds: back to Rocket Crew",
    start: "swap.06-everyone-in",
    steps: [{ device: "phone", bot: "undo-switch", mark: "Back to it: Bake Shop saves day 4, mission 6 resumes everywhere", wait: 5600 }],
  },
  {
    id: "word-duel",
    flow: "word-duel",
    label: "Word Duel: Nana's game, play CRANE, back to the list",
    start: "word-duel.01-list",
    steps: [
      { device: "phone", bot: "duel-wd-1", mark: "Your turn against Nana" },
      { device: "phone", bot: "rack-C", mark: "Tap tiles into the glowing squares", wait: 700 },
      { device: "phone", bot: "rack-R", wait: 700 },
      { device: "phone", bot: "rack-A", wait: 700 },
      { device: "phone", bot: "rack-N", mark: "CRANE on the triple word: 27", wait: 1200 },
      { device: "phone", bot: "play", mark: "Play it. Sent to Nana; Mom's game is next", wait: 1800 },
      { device: "phone", bot: "all-games", mark: "Back to the list: Nana's game is now waiting on her" },
    ],
  },
  {
    id: "game-night",
    flow: "game-night",
    label: "A new Hearthisle night across three homes, while turn 14 waits",
    start: "game-night.01-lane",
    steps: [
      { device: "phone", bot: "night-new", mark: "Game nights → New. The paused night (turn 14) keeps its place", wait: 1800 },
      { device: "phone", bot: "invite-send", mark: "Invite the Okafors and Nana & Pop. Other homes see 'The Mumms · blue', never the kids", wait: 1200 },
      { device: "phone", bot: "invite-preview", mark: "See what Nana & Pop see: the invite, their accept or decline", wait: 2200 },
      { device: "phone", bot: "preview-close", mark: "Both homes say yes while we look", wait: 1400 },
      { device: "phone", bot: "night-seats", mark: "Seats: a seat is a person or a whole home. Jonathan + Juneau share blue", wait: 1800 },
      { device: "phone", bot: "seats-next", mark: "Where each home plays: our TV, their TV, Nana & Pop on phones", wait: 1800 },
      { device: "phone", bot: "night-start", mark: "Start: turn 1 on our TV; the Okafors roll first, ours comes next", wait: 5200 },
      { device: "phone", bot: "night-back", mark: "Home: two game nights, one live, one paused", wait: 1600 },
    ],
  },
  {
    id: "game-night-resume",
    flow: "game-night",
    label: "Next Friday 8:00: resume turn 14, our roll, pause again",
    start: "game-night.14-everyone-back",
    steps: [
      { device: "phone", bot: "night-resume", mark: "Every home is back: resume turn 14 on the TV. Nana & Pop roll", wait: 4200 },
      { device: "phone", bot: "night-pause", mark: "Our roll came round; bedtime. Pause: it resumes when everyone's back", wait: 1800 },
      { device: "phone", bot: "night-back", mark: "Home: the night waits for next Friday", wait: 1400 },
    ],
  },
  {
    id: "your-turn",
    flow: "world-clock",
    label: "A push on Dad's phone → the move → next game waiting, across games",
    start: "world-clock.01-push-duel",
    steps: [
      { device: "phone", bot: "push-open", mark: "Nana played. The push lands on Dad's phone only, and opens her board", wait: 1400 },
      { device: "phone", bot: "rack-C", mark: "Tiles into the glowing squares", wait: 600 },
      { device: "phone", bot: "rack-R", wait: 600 },
      { device: "phone", bot: "rack-A", wait: 600 },
      { device: "phone", bot: "rack-N", wait: 1000 },
      { device: "phone", bot: "play", mark: "CRANE for 27. Next waiting on you, whatever the game", wait: 1800 },
      { device: "phone", bot: "duel-next", mark: "Next: Mom's game", wait: 1600 },
      { device: "phone", bot: "duel-back", mark: "Back to the list", wait: 1200 },
    ],
  },
  {
    id: "tonight",
    flow: "tonight",
    label: "Friday night: who's here, Play on TV, devices join by name",
    start: "tonight.01-open-app",
    steps: [
      { device: "phone", bot: "couch-who", mark: "Who's on the couch tonight? Mom's out; Juneau and Ava are in", wait: 1600 },
      { device: "phone", bot: "who-done", mark: "Three on the couch", wait: 1000 },
      { device: "phone", bot: "play-on-tv", mark: "Play on TV: the living room TV connects, the iPads join by name", wait: 4600 },
    ],
  },
  {
    id: "first-run",
    flow: "first-run",
    label: "First run: the TV, who plays here (stickers), pair the kids' iPads",
    start: "first-run.01-welcome",
    steps: [
      { device: "phone", bot: "setup-start", mark: "Set up the living room: the phone looks for the TV on this Wi-Fi", wait: 2200 },
      { device: "phone", bot: "connect-living", mark: "Living room TV: connect once. Nothing is installed on it", wait: 2000 },
      { device: "phone", bot: "setup-people", mark: "Who plays here? Jonathan is in; Family Sharing suggests the rest", wait: 1200 },
      { device: "phone", bot: "add-mom", wait: 600 },
      { device: "phone", bot: "add-juneau", wait: 600 },
      { device: "phone", bot: "add-ava", mark: "Ages decide seats: grown-ups read, kids get controls with no words", wait: 1200 },
      { device: "phone", bot: "sticker-mom", mark: "Everyone picks a sticker; it's how every screen shows them", wait: 1400 },
      { device: "phone", bot: "pick-owl", wait: 1000 },
      { device: "phone", bot: "setup-ipads", mark: "Pair each kid's iPad once", wait: 1000 },
      { device: "phone", bot: "pair-juneau", mark: "On Juneau's iPad: opengame.org, tap his dragon", wait: 1200 },
      { device: "phone", bot: "confirm-juneau", mark: "That's Juneau's iPad. Paired, with an Unpair any time", wait: 1000 },
      { device: "phone", bot: "pair-ava", wait: 800 },
      { device: "phone", bot: "confirm-ava", wait: 1000 },
      { device: "phone", bot: "setup-done", mark: "The living room: TV, four stickers, two iPads", wait: 1600 },
      { device: "phone", bot: "setup-finish", mark: "Home. Tonight starts with who's on the couch", wait: 1400 },
    ],
  },
  {
    id: "continue",
    flow: "continue",
    label: "Bake Shop: start a new bakery, keeping day 4",
    start: "continue.01-start",
    steps: [
      { device: "phone", bot: "start-new", mark: "Continue would pick up day 4. New asks what happens to day 4 first", wait: 1800 },
      { device: "phone", bot: "fate-replace", mark: "Replace says plainly: day 4 is gone for good", wait: 1600 },
      { device: "phone", bot: "fate-keep", mark: "Keep it as a second save instead", wait: 1200 },
      { device: "phone", bot: "new-confirm", mark: "A new bakery on the TV; day 4 is still there for Continue", wait: 2600 },
    ],
  },
  {
    id: "turn-arrives",
    flow: "world-clock",
    label: "A move arrives while Home is open",
    start: "home.09-move-incoming",
    steps: [
      { device: "phone", bot: "turn-wd-3", mark: "Tunde played. His whale hops down the path onto his board; Your turn counts 3", wait: 1800 },
      { device: "phone", bot: "duel-back", mark: "Word Duel: his game is under Your turn, with JAZZ on his board", wait: 1400 },
    ],
  },
];
